image: node

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build

test-jest:
  stage: test
  script:
    - npm install
    - npm test

test-postman:
  stage: test
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - newman run postman/collections/phase_2_syrian_refugee_api.json

gui-tests:
    image: joyzoursky/python-chromedriver:3.9-selenium
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - python3 src/gui-tests.py

