image: node

stages:
  - build
  - test

# before_script:
#   - npm install

build:
  stage: build
  script:
    - npm install
    - npm run build

test-jest:
  stage: test
  script:
    - npm install
    - npm test

test-postman:
  stage: test
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - newman run postman/collections/phase_2_syrian_refugee_api.json

backend_unit_tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - python3 backend/tests.py

gui-tests:
    image: joyzoursky/python-chromedriver:3.9-selenium
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - python3 src/gui-tests.py
