image: node

stages:
  - build
  - test

# before_script:
#   - npm install

build:
  stage: build
  script:
    - npm install
    - npm run build

test-jest:
  stage: test
  script:
    - npm install
    - npm test

gui-tests:
  stage: test
  image: python:3.10
  variables:
    CHROMEDRIVER_VERSION: "114.0.5735.90"
  script:
    - apt-get update && apt-get install -y unzip
    - CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
    - wget $CHROMEDRIVER_URL -O chromedriver.zip
    - unzip chromedriver.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/chromedriver
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python ./src/gui-tests.py
  
